In [3]:
import pandas as pd

data = {
    'name': ['Kim', 'Lee', 'Park'],
    'age': [25, 30, 35],
    'city': ['Seoul', 'Busan', 'Incheon']
}
df = pd.DataFrame(data)
df

   name  age     city
0   Kim   25    Seoul
1   Lee   30    Busan
2  Park   35  Incheon

In [5]:
data = [
    {'name': 'Kim', 'age': 25, 'city': 'Seoul'},
    {'name': 'Lee', 'age': 30, 'city': 'Busan'},
    {'name': 'Park', 'age': 35, 'city': 'Incheon'}
]
df = pd.DataFrame(data)
df

   name  age     city
0   Kim   25    Seoul
1   Lee   30    Busan
2  Park   35  Incheon

In [10]:
data = [
    ['Kim', 25, 'Seoul'],
    ['Lee', 30, 'Busan'],
    ['Park', 35, 'Incheon']
]
df = pd.DataFrame(data, 
                  columns=['name', 'age', 'city']
                  )

df

   name  age     city
0   Kim   25    Seoul
1   Lee   30    Busan
2  Park   35  Incheon

In [5]:
s1 = pd.Series(['Kim', 'Lee', 'Park'], name='name')
s2 = pd.Series([25, 30, 35], index=['a','b','c'])
df = pd.DataFrame({'name': s1, 'age': s2})

df

   name   age
0   Kim   NaN
1   Lee   NaN
2  Park   NaN
a   NaN  25.0
b   NaN  30.0
c   NaN  35.0

In [7]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
df = pd.DataFrame(arr, columns=['A', 'B', 'C'])

df

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [20]:
# df.shape        # (행 수, 열 수)
# df.size         # 전체 요소 개수
# df.ndim         # 차원 (항상 2)
# df.index        # 인덱스 객체
# df.columns      # 컬럼 객체
# df.values       # NumPy 배열
# df.dtypes       # 각 컬럼의 데이터 타입

data = {
    'city': ['서울','대전','대구','부산'],
    'data1': np.random.randint(1000,10000,4),
    'data2': np.random.randn(4)
}

df = pd.DataFrame(data)
df.dtypes

city      object
data1      int32
data2    float64
dtype: object

In [24]:
df.info()       # 전체 정보 (타입, 결측치 등)
df.describe(include='all')   # 기술통계 (수치형 컬럼만)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   city    4 non-null      object
 1   data1   4 non-null      int32
 2   data2   4 non-null      float64
dtypes: float64(1), int32(1), object(1)
memory usage: 208.0+ bytes

       city       data1     data2
count     4     4.00000  4.000000
unique    4         NaN       NaN
top      서울         NaN       NaN
freq      1         NaN       NaN
mean    NaN  4506.75000 -0.434557
std     NaN  1935.14881  1.027478
min     NaN  2336.00000 -1.510971
25%     NaN  3266.00000 -1.101184
50%     NaN  4491.50000 -0.531733
75%     NaN  5732.25000  0.134895
max     NaN  6708.00000  0.836211

In [ ]:
data = {
    'city' : ['서울','대전','대구','부산'],
    'data1' : np.random.randint(100000,1000000,4),
    'data2' : np.random.randn(4),
}
df = pd.DataFrame(data)

df['salary'] = [3000, 4000, 5000,6000]
df['salary2'] = 000

df.drop('salary2',axis=1,inplace=True)

  city   data1     data2  salary
0   서울  723567  0.952732    3000
1   대전  900042 -1.460526    4000
2   대구  266665  0.002211    5000
3   부산  633675 -1.574400    6000

In [45]:
import pandas as pd

file_path = '소상공인시장진흥공단_전국 온누리상품권 가맹점 현황_20250731 (1).csv'
df = pd.read_csv(file_path)
df.head()

df.isna().sum()    # 결측치 개수
df.describe()      # 기술 통계(숫자 컬럼)
df.describe(include=object)     # 기술 통계(문자 컬럼)
df.info()    # 데이터 프레임 정보
df.rename(columns={'소속 시장명(또는 상점가)':'시장명-상점가'})   # 컬럼명 변경
df[['소재지','취급품목','등록년도']].count()   # 각 컬럼의 개수
df[['소재지','취급품목','등록년도']].dtypes    # 각 컬럼의 유형
df[['지류형 가맹 여부']].isin(['N'])    # 지류형 가맹여부 N인 데이터프레임
df.drop('등록년도',axis=1)    # 컬럼 삭제
df.drop('등록년도',axis=1,inplace=True)   # 컬럼 삭제 원본 반영

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150541 entries, 0 to 150540
Data columns (total 7 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   가맹점명            150501 non-null  object
 1   소속 시장명(또는 상점가)  150541 non-null  object
 2   소재지             150541 non-null  object
 3   취급품목            150248 non-null  object
 4   지류형 가맹 여부       150541 non-null  object
 5   디지털형 가맹 여부      150541 non-null  object
 6   등록년도            150541 non-null  int64
dtypes: int64(1), object(6)
memory usage: 8.0+ MB

In [ ]:
file_path = '소상공인시장진흥공단_전국 온누리상품권 가맹점 현황_20250731 (1).csv'
df = pd.read_csv(file_path)

df2 = df.head().copy()
df3 = df2.set_index('소재지').copy

In [75]:
sample_df1 = df.iloc[-5:,:2]
sample_df2 = df.iloc[:5,-2:]

In [78]:
df_merge = pd.concat([sample_df1,sample_df2],axis=1)
df_merge.info

<bound method DataFrame.info of          가맹점명  소속 시장명(또는 상점가) 디지털형 가맹 여부    등록년도
150536   태성마트  단양구경시장(단양인정시장)        NaN     NaN
150537   동산닭집  단양구경시장(단양인정시장)        NaN     NaN
150538  파마미용실  단양구경시장(단양인정시장)        NaN     NaN
150539   두메하누  단양구경시장(단양인정시장)        NaN     NaN
150540  단양보리밥  단양구경시장(단양인정시장)        NaN     NaN
0         NaN             NaN          Y  2025.0
1         NaN             NaN          Y  2025.0
2         NaN             NaN          Y  2025.0
3         NaN             NaN          Y  2025.0
4         NaN             NaN          Y  2025.0>

In [ ]:
set_ind = df_merge.reset_index()
set_ind.rename(columns={'index':'data'},inplace=True)

TypeError: DataFrame.set_index() missing 1 required positional argument: 'keys'