In [ ]:
corpus = [
    "나는 자연어 처리를 공부한다",
    "자연어 처리는 재미있다",
    "나는 자연어를 좋아하고 자연어 처리를 실습한다"
]

# 공백 기반으로 토큰 분류
docs = [doc.split() for doc in corpus]
N = len(docs)
# 고유어휘 vacabulary 구축
vocab = list(set([word for doc in docs for word in doc]))
vocab

['재미있다', '좋아하고', '처리는', '실습한다', '나는', '처리를', '공부한다', '자연어를', '자연어']

In [5]:
import math

# tf 함수
def compute_TF(term, document):
    return document.count(term)
# df 함수
def compute_DF(term, documents):
    return sum([1 for doc in documents if term in doc])

# idf 함수
def compute_IDF(term, documents):
    df = compute_DF(term, documents)
    return math.log((N+1) / (df+1)) + 1


def compute_TFIDF(term,document,docs):
    tf = compute_TF(term,document)
    idf = compute_IDF(term,docs)
    return tf*idf

In [6]:
word1 = '자연어'
word2 = '공부한다'

print(f"TF-IDF of '{word1}' in document 1: {compute_TFIDF(word1, docs[0], docs)}")
print(f"TF-IDF of '{word2}' in document 1: {compute_TFIDF(word2, docs[0], docs)}")

TF-IDF of '자연어' in document 1: 1.0
TF-IDF of '공부한다' in document 1: 1.6931471805599454

In [11]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
import pandas as pd

cv = CountVectorizer()
dtm = cv.fit_transform(corpus)
print(f'Scikit-Learn 어휘(Feature name) : {cv.get_feature_names_out()}')
df_dtm = pd.DataFrame(dtm.toarray(), columns=cv.get_feature_names_out())
print(corpus[0])
print(corpus[1])
print(corpus[2])
df_dtm

Scikit-Learn 어휘(Feature name) : ['공부한다' '나는' '실습한다' '자연어' '자연어를' '재미있다' '좋아하고' '처리는' '처리를']
나는 자연어 처리를 공부한다
자연어 처리는 재미있다
나는 자연어를 좋아하고 자연어 처리를 실습한다

   공부한다  나는  실습한다  자연어  자연어를  재미있다  좋아하고  처리는  처리를
0     1   1     0    1     0     0     0    0    1
1     0   0     0    1     0     1     0    1    0
2     0   1     1    1     1     0     1    0    1

In [12]:
# tf-idf
tfidf_vec = TfidfVectorizer()
tfidf_matrix = tfidf_vec.fit_transform(corpus)  # L2정규화 포함

df_tfidf = pd.DataFrame(tfidf_matrix.toarray(), columns=tfidf_vec.get_feature_names_out() )
df_tfidf

,공부한다,나는,실습한다,자연어,자연어를,재미있다,좋아하고,처리는,처리를
0,0.631745,0.480458,0.00000,0.373119,0.00000,0.000000,0.00000,0.000000,0.480458
1,0.000000,0.000000,0.00000,0.385372,0.00000,0.652491,0.00000,0.652491,0.000000
2,0.000000,0.358291,0.47111,0.278245,0.47111,0.000000,0.47111,0.000000,0.358291