In [ ]:
# 결측치: 데이터 수집 저장 과정에서 값이 누락된것
# 0 = False, 1 = True

In [ ]:
import numpy as np
import pandas as pd

samples =  np.array(['사과','바나나','딸기','사과','오렌지'])
df = pd.DataFrame(samples,columns='과일')
df['과일'].mode()

In [ ]:
# 결측치 탐지
import numpy as np
import pandas as pd

df = pd.read_csv('data/messy_data.csv')
# df.head()

# 원본 데이터 모양
df.shape
# 결측치 개수
df.isna().sum().sum()
# 결측치 비율
(df.isna().mean()*100).round(2)
# 결측치 포함 행의 개수
df.isna().any(axis=1).sum()

np.int64(22)

In [24]:
df.head().isna().astype(int)

   id  name  age  salary  score  department
0   0     0    0       0      0           0
1   0     0    0       0      0           0
2   0     0    0       0      0           0
3   0     0    0       0      0           0
4   0     0    0       0      0           0

In [ ]:
# 결측치 삭제
# 결측치 있는 행만 출력
df[df.isna().any(axis=1)]
# 결측치 하나라도 있는 행 삭제
df1 = df.dropna(how='any')
# 모든 값이 nan인 행 삭제
df2 = df.dropna(how='all')
# 특정 컬럼 기준 삭제
df3 = df.dropna(subset=['age','salary'])
# thresh - 최소 N개 유효값이 있어야 보존 (살아있는 값만 보존한다는 개념)
df4 = df.dropna(thresh=5)
df4[df4.isna().any(axis=1)]

In [51]:
# 결측치 대치
# 고정값으로 대치
df_fill_zero = df.copy()
s = df_fill_zero.isna().any()
df_fill_zero['score'].fillna(df_fill_zero['score'].median())
dept_mode = df_fill_zero['department'].mode()[0]
df_fill_zero['age'].bfill()

0      56.0
1      46.0
2      32.0
3      60.0
4      25.0
       ...
107    38.0
108    28.0
109    56.0
110    41.0
111    59.0
Name: age, Length: 112, dtype: float64

In [ ]:
import numpy as np
import pandas as pd

df = pd.read_csv('data/messy_data.csv')
# df.head(2)

# 보간 : 선형보간 / 다항식 보간
df['score'].interpolate(method='polynomial',order=2)

0       17.500000
1       98.220000
2       51.660000
3       26.080000
4       99.630000
          ...
107    113.323101
108     70.040000
109     17.500000
110     66.900000
111     49.390000
Name: score, Length: 112, dtype: float64

In [ ]:
import numpy as np
import pandas as pd

df = pd.read_csv('C:/git_test/pandsa/data/소상공인시장진흥공단_상가(상권)정보_경기_202512.csv', low_memory=False)
df.head(2)

In [11]:
len(df.columns)

39

In [33]:
# 이상치 탐지
%pwd
%pwd
import pandas as pd
import numpy as np
df = pd.read_csv(r'data\messy_data.csv')
numeric_cols = df.describe().columns
# 이상치 탐지를 위해서 결측치를 중앙값으로 대처
for col in numeric_cols:
    df[col] = df[col].fillna(df[col].median())

In [38]:
# IQR 
# IQR 
def detect_outlier_iqr(data,column):
    Q1 = data[column].quantile(0.25)
    Q3 = data[column].quantile(0.75)
    IQR = Q3-Q1
    lower = Q1 - IQR * 1.5
    upper = Q3 + IQR * 1.5
    outlier_mask = (data[column] > upper ) | (data[column] < lower)
    return outlier_mask,lower,upper,Q1,Q3,IQR

In [39]:
iqr_df = df.copy()

total_removed_counts = 0
for colname in numeric_cols:    
    outlier_mask,lower,upper,Q1,Q3,IQR =  detect_outlier_iqr(iqr_df,colname)
    print(f'컬럼명 : {colname}')
    print(f'이상치 개수 : {outlier_mask.sum()}')
    print('-'*50)
    before = len(iqr_df)
    iqr_df = iqr_df[~outlier_mask]
    removed = before - len(iqr_df)
    total_removed_counts += removed

print(f'IQR 제거후 shape {iqr_df.shape}')
print(f'총 제거수 : {total_removed_counts}')

컬럼명 : age
이상치 개수 : 4
--------------------------------------------------
컬럼명 : salary
이상치 개수 : 6
--------------------------------------------------
컬럼명 : score
이상치 개수 : 0
--------------------------------------------------
IQR 제거후 shape (102, 6)
총 제거수 : 10

In [42]:
# 데이터가 정규분포를 따른다고 가정
from scipy import stats
# (각 요소 - 평균) / 표준편차
def detect_outlier_zscore(data, column, threshold=3):
    z_score = np.abs(stats.zscore(data[column].dropna()))
    return z_score > threshold

In [ ]:
for col in numeric_cols:
    before = len(df)
    zscore_index = detect_outlier_zscore(df, col)
    df = df[zscore_index]
    removed = before - len(df)
    print(col, removed)

age 102
salary 102
score 102

In [ ]:
# 이상치 탐색 (수치형)
# 원본이 아닌 복사본으로 결측치 이상치 탐색 대처
# IQR
# Z-score

In [52]:
import pandas as pd

filepath = 'data/아파트(매매)_실거래가_20260403104248.csv'
df = pd.read_csv(filepath,encoding='cp949',header=15)

In [67]:
df['거래금액(만원)'] = df['거래금액(만원)'].str.replace(',','').astype(int)

In [68]:
df.describe()

,NO,본번,부번,전용면적(㎡),계약년월,계약일,거래금액(만원),층,건축년도
count,2968.000000,2968.000000,2968.000000,2968.000000,2968.000000,2968.000000,2.968000e+03,2968.000000,2968.000000
mean,1484.500000,538.760782,3.614218,86.399945,202521.773922,16.478437,2.879723e+05,9.196765,2000.747305
std,856.932125,355.302426,9.308358,39.168293,33.462621,9.043665,1.886570e+05,6.884455,12.659291
min,1.000000,2.000000,0.000000,12.449000,202504.000000,1.000000,1.350000e+04,1.000000,1976.000000
25%,742.750000,187.000000,0.000000,59.847500,202506.000000,9.000000,1.610000e+05,4.000000,1992.000000
50%,1484.500000,579.000000,0.000000,84.460000,202508.000000,17.000000,2.550000e+05,8.000000,2002.000000
75%,2226.250000,746.000000,1.000000,107.380000,202511.000000,25.000000,3.592500e+05,12.000000,2012.000000
max,2968.000000,1284.000000,74.000000,273.960000,202603.000000,31.000000,1.900000e+06,64.000000,2025.000000

In [69]:
# 이상치가 아닌 clean area 해당하는 시군구
# 이상치로 판단되는 시군구

outliner_index = detect_outlier_iqr(df,'거래금액(만원)')[0]
df[outliner_index]['시군구'].unique(),lower,upper

(array(['서울특별시 강남구 압구정동', '서울특별시 강남구 삼성동', '서울특별시 강남구 청담동',
        '서울특별시 강남구 신사동', '서울특별시 강남구 대치동', '서울특별시 강남구 도곡동'], dtype=object),
 np.float64(-26.08500000000001),
 np.float64(123.13500000000002))

In [71]:
df[outliner_index]['시군구'].unique()

array(['서울특별시 강남구 압구정동', '서울특별시 강남구 삼성동', '서울특별시 강남구 청담동',
       '서울특별시 강남구 신사동', '서울특별시 강남구 대치동', '서울특별시 강남구 도곡동'], dtype=object)

In [72]:
df[detect_outlier_zscore(df,'거래금액(만원)')]['시군구'].unique()

array(['서울특별시 강남구 삼성동', '서울특별시 강남구 압구정동', '서울특별시 강남구 청담동'], dtype=object)

In [84]:
import os
import pandas as pd

filepath = 'data/messy_data.csv'
df = pd.read_csv(filepath)
df.head(2)

   id    name   age   salary  score department
0   1  user_1  56.0  59545.0  17.50        마케팅
1   2  user_2  46.0  36399.0  98.22         영업

In [ ]:
dup_by_id = df.duplicated(subset=['id']).sum()
dup_by_name_dept = df.duplicated(subset=['name','department']).sum()
df_keep_first = df.drop_duplicates(keep='first')
df_keep_last = df.drop_duplicates(keep='last')
df.shape, df_keep_first.shape, df_keep_last.shape

df_keep_none = df.drop_duplicates(keep=False)
df_unique_id = df.drop_duplicates(subset=['id'],keep='last')

(100, 6)

In [ ]:
df_keep_first.duplicated().sum()

np.int64(0)