In [ ]:
# 정적페이지 크롤링
# %conda install requests beautifulsoup4 lxml

#동적페이지 크롤링
# %conda install selenium

# 데이터처리
# %conda install pandas

%conda install requests beautifulsoup4 lxml selenium pandas

In [ ]:
import requests
from bs4 import BeautifulSoup

# http 요청
url = 'http://example.com/'
response = requests.get(url)
response.text

# html 파싱
soup = BeautifulSoup(response.text,'lxml')

#
title = soup.find('h1')
print(title)

In [ ]:
from bs4 import BeautifulSoup
html = """
<html>
  <head><title>샘플 페이지</title></head>
  <body>
    <h1 class="main-title">제목</h1>
    <div id="content">
      <p class="text">첫 번째 문단</p>
      <p class="text">두 번째 문단</p>
      <a href="/page1">링크1</a>
      <a href="/page2">링크2</a>
    </div>
  </body>
</html>
"""
soup = BeautifulSoup(html,'lxml')

# 데이터 찾기 메서드

In [ ]:
# 태그로 찾가
title = soup.find('h1')
print(title)

for p in soup.find_all('p'):
    print(p.text)

# css 선택자 (select)
# class로 찾기
texts = soup.select('.text')

# id로 찾기
content = soup.select('#content')

# 복합 선택자
links = soup.select('div#content a')

# 태그명으로 찾기
soup.select('p')

In [ ]:
html = """
<html>
  <body>
    <a href="/page1">링크1</a>
    <a href="/page2">링크2</a>
    <img src="/image1.jpg" alt="이미지1">
    <img src="/image2.jpg" alt="이미지2">
  </body>
</html>
"""
# soup = BeautifulSoup(html,'lxml')
soup = BeautifulSoup(html,'html.parser')

# href 속성 가져오기
link = soup.find('a')
print(link['href'])
print(link.get('href')) # 안전

# 모든 링크 추출
for p in soup.select('a'):
    print(p.get('href'))

# 실제 사이트

In [ ]:
import requests
from bs4 import BeautifulSoup
url = 'https://books.toscrape.com/'
response = requests.get(url)
response.raise_for_status() #에러체크

#책 하나의 제목 추출
soup = BeautifulSoup(response.text,'lxml')
#soup.select('article.product_pod')[0].find('h3').find('a').get('title')
soup.select('article.product_pod')[0].select_one('h3 a').get('title')

In [ ]:
import requests
from bs4 import BeautifulSoup
url = 'https://books.toscrape.com/'
response = requests.get(url)
response.raise_for_status() #에러체크

#페이지 내 모든 책 제목, 링크 추출
soup = BeautifulSoup(response.text,'lxml')
titles,links = [], []
for li in soup.select('ol.row li'):
    #print(li.select('article.product_pod')[0].select_one('h3 a').get('title'))
    titles.append(li.select('article.product_pod')[0].select_one('h3 a').get('title'))
    links.append('https://books.toscrape.com/'+ (li.select('article.product_pod')[0].select_one('h3 a').get('href')))

In [30]:
import pandas as pd
data = {
    'title': titles,
    'links': links
}
pd.DataFrame(data)

,title,links
0,A Light in the Attic,https://books.toscrape.com/catalogue/a-light-i...
1,Tipping the Velvet,https://books.toscrape.com/catalogue/tipping-t...
2,Soumission,https://books.toscrape.com/catalogue/soumissio...
3,Sharp Objects,https://books.toscrape.com/catalogue/sharp-obj...
4,Sapiens: A Brief History of Humankind,https://books.toscrape.com/catalogue/sapiens-a...
5,The Requiem Red,https://books.toscrape.com/catalogue/the-requi...
6,The Dirty Little Secrets of Getting Your Dream...,https://books.toscrape.com/catalogue/the-dirty...
7,The Coming Woman: A Novel Based on the Life of...,https://books.toscrape.com/catalogue/the-comin...
8,The Boys in the Boat: Nine Americans and Their...,https://books.toscrape.com/catalogue/the-boys-...
9,The Black Maria,https://books.toscrape.com/catalogue/the-black...
10,"Starving Hearts (Triangular Trade Trilogy, #1)",https://books.toscrape.com/catalogue/starving-...
11,Shakespeare's Sonnets,https://books.toscrape.com/catalogue/shakespea...
12,Set Me Free,https://books.toscrape.com/catalogue/set-me-fr...
13,Scott Pilgrim's Precious Little Life (Scott Pi...,https://books.toscrape.com/catalogue/scott-pil...
14,Rip it Up and Start Again,https://books.toscrape.com/catalogue/rip-it-up...
15,Our Band Could Be Your Life: Scenes from the A...,https://books.toscrape.com/catalogue/our-band-...
16,Olio,https://books.toscrape.com/catalogue/olio_984/...
17,Mesaerion: The Best Science Fiction Stories 18...,https://books.toscrape.com/catalogue/mesaerion...
18,Libertarianism for Beginners,https://books.toscrape.com/catalogue/libertari...
19,It's Only the Himalayas,https://books.toscrape.com/catalogue/its-only-...

In [ ]:
# 모든 페이지 정보 추출

import requests
from bs4 import BeautifulSoup
titles,links = [], []

for pagenum in range(1,51):
    url = 'https://books.toscrape.com/'
    response = requests.get(url)
    response.raise_for_status() #에러체크

    #페이지 내 모든 책 제목, 링크 추출
    soup = BeautifulSoup(response.text,'lxml')

    for li in soup.select('ol.row li'):
    #print(li.select('article.product_pod')[0].select_one('h3 a').get('title'))
        titles.append(li.select('article.product_pod')[0].select_one('h3 a').get('title'))
        links.append('https://books.toscrape.com/'+ (li.select('article.product_pod')[0].select_one('h3 a').get('href')))

In [33]:
import pandas as pd
data = {
    'title': titles,
    'links': links
}
pd.DataFrame(data)

,title,links
0,A Light in the Attic,https://books.toscrape.com/catalogue/a-light-i...
1,Tipping the Velvet,https://books.toscrape.com/catalogue/tipping-t...
2,Soumission,https://books.toscrape.com/catalogue/soumissio...
3,Sharp Objects,https://books.toscrape.com/catalogue/sharp-obj...
4,Sapiens: A Brief History of Humankind,https://books.toscrape.com/catalogue/sapiens-a...
...,...,...
995,Our Band Could Be Your Life: Scenes from the A...,https://books.toscrape.com/catalogue/our-band-...
996,Olio,https://books.toscrape.com/catalogue/olio_984/...
997,Mesaerion: The Best Science Fiction Stories 18...,https://books.toscrape.com/catalogue/mesaerion...
998,Libertarianism for Beginners,https://books.toscrape.com/catalogue/libertari...
999,It's Only the Himalayas,https://books.toscrape.com/catalogue/its-only-...

In [ ]:
# 네이버 뉴스 헤드라인 크롤링

import requests
from bs4 import BeautifulSoup
url = 'https://news.naver.com/section/100'

response = requests.get(url)

soup = BeautifulSoup(response.text, 'html.parser')

result = soup.select_one('div.section_article.as_headline._TEMPLATE')
for data in result.select('ul>li'):
    print(data.select_one('strong.sa_text_strong').text)

국힘 박수민 "오세훈 한강버스 '전면 재검토'하겠다"…서울시장 출마 선언
주진우 의원, 천안함 16주기 맞아 故 문규석 원사 모교 방문
'싹다' 핵잠으로 바꾼다…中, 美 해군력에 도전
'룸살롱 폭행·억대 체납' 이혁재가 심사위원?…국힘 청년 오디션 '시끌'
주한이란대사 "이란 내 한국인 대피 협조"…美와 합의는 부인
‘5월1일 노동절 법정공휴일법’ 행안위 통과…올해 시행 유력
이재명 대통령 1년 전보다 재산 18억 9천만원 증가한 49억 7천만원 신고…저서 저작권 소득만 15억 6천여만원
주호영 “무소속 출마” 언급…대구시장 ‘3자 대결’ 되나
장동혁 "이재명정부, 추경만 하면 위기 해소될 것처럼 국민 기만"
1587억 재산 신고한 이세웅 평안북도 지사…'다주택왕' 조성명 강남구청장