In [1]:
corpus = [
    "나는 자연어 처리를 공부한다",
    "자연어 처리는 재미있다",
    "나는 자연어를 좋아하고 자연어 처리를 실습한다"
]

# 공백 기준으로 토큰분류
docs = [doc.split() for doc in corpus]
N = len(docs)
# 고유어휘 vocabury 구축
vocab = list(set(word for doc in docs for word in doc))
vocab

['좋아하고', '처리는', '나는', '자연어', '실습한다', '자연어를', '재미있다', '공부한다', '처리를']

In [2]:
import math
# tf 함수
def compute_TF(term, document):
    return document.count(term)
# df 함수
def compute_DF(term, docs):
    return sum([1 for doc in docs if term in doc])

def compute_IDF(term, docs):
    df = compute_DF(term, docs)
    return math.log( (N+1)/(df+1)) + 1

def compute_TFIDF(term, document, docs):
    tf = compute_TF(term, document)
    idf = compute_IDF(term, docs)
    return tf * idf

In [3]:
# 첫번째 문장에 대해서 word1, word2의 tf-idf
word1 = '자연어'
word2 = '공부한다'
print(docs[0])
print(f'word1 tf-idf : {compute_TFIDF(word1, docs[0], docs)}')
print(f'word2 tf-idf : {compute_TFIDF(word2, docs[0], docs)}')

['나는', '자연어', '처리를', '공부한다']
word1 tf-idf : 1.0
word2 tf-idf : 1.6931471805599454

In [4]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
import pandas as pd

cv = CountVectorizer()
dtm = cv.fit_transform(corpus)
print(f'Scikit-Learn 어휘(Feature name) : {cv.get_feature_names_out()}')
df_dtf = pd.DataFrame(dtm.toarray(), columns=cv.get_feature_names_out())
print(corpus[0])
print(corpus[1])
print(corpus[2])
df_dtf

Scikit-Learn 어휘(Feature name) : ['공부한다' '나는' '실습한다' '자연어' '자연어를' '재미있다' '좋아하고' '처리는' '처리를']
나는 자연어 처리를 공부한다
자연어 처리는 재미있다
나는 자연어를 좋아하고 자연어 처리를 실습한다

   공부한다  나는  실습한다  자연어  자연어를  재미있다  좋아하고  처리는  처리를
0     1   1     0    1     0     0     0    0    1
1     0   0     0    1     0     1     0    1    0
2     0   1     1    1     1     0     1    0    1

In [5]:
# tf-idf
tfidf_vec = TfidfVectorizer()
tfidf_matrix = tfidf_vec.fit_transform(corpus) # L2정규화 포함

df_tfidf = pd.DataFrame(tfidf_matrix.toarray(), columns=tfidf_vec.get_feature_names_out())
df_tfidf

       공부한다        나는     실습한다       자연어  ...      재미있다     좋아하고       처리는       처리를
0  0.631745  0.480458  0.00000  0.373119  ...  0.000000  0.00000  0.000000  0.480458
1  0.000000  0.000000  0.00000  0.385372  ...  0.652491  0.00000  0.652491  0.000000
2  0.000000  0.358291  0.47111  0.278245  ...  0.000000  0.47111  0.000000  0.358291

[3 rows x 9 columns]